### ISSUE TITLE
Suggestion: Avoid spaces in filenames

### ISSUE THREAD

**Issue by abhilash1in** [malikshubham827/get-me-through#1]
Eg. known_people/Narendra Modi.jpg

**Comment by malikshubham827** [comment]
Yeah, I thought about that. I thought to use the common '-' in the names, but I want to show the name in the window that shows the identified person with face detected with green border and name displayed as `Shubham Malik` instead of any other form as people are used to seeing the name with space. So in all places, i.e. 
* known_folder
* learnt data i.e. people's name
* in the MongoDB data base 
 * info of person in front-end on successful authentication 
* Real time video stream with face detection and recognition along with name 
all of them use ` ` in between names.

Yeah, it may cause pain in case of CLI but as I created this GUI web app so it won't have much effect.

If that can have any performance improvements, then it can be changed. Rest is personal preference.

Thanks for the suggestion. Do tell me if there is any other or I may close it.

**Comment by abhilash1in** [comment]
You can try a simple fix. Use `-` or `_` with lower case in all places and while displaying on the gui, parse it (JavaScript?) to replace the `-` or `_` with a space and convert the text to Title Case!

**Comment by malikshubham827** [comment]
Yeah as I said it is just a matter of personal preference. I preferred space between name while showing it to the user, so I used it everywhere in the app. Had it been using some functionality where user has to use the command line, then it would be a must use case to use `-` or `_` (for comfort while typing).

Yeah I may do that, but it would make it a little bit time consuming ( a tiny bit, at-least we are traversing the string once) although insignificant. I preferred the above as it is **short**.

In the future maybe for an additional functionality, it might be changed if necessary.

**Comment by abhilash1in** [comment]
👍
